from django.db import models
from django.contrib.auth.models import AbstractUser
#table admin:
class Admin(models.Model):
    name = models.CharField(max_length=40, null=True, blank=True)
    email = models.EmailField(max_length=40, unique=True, null=True, blank=True)
    username = models.CharField(max_length=40, unique=True, null=True, blank=True)
    email_verified_at = models.DateTimeField(null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    password = models.CharField(max_length=255)
    remember_token = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
 #table admin_notifications:
class AdminNotification(models.Model):
    user_id = models.IntegerField(default=0)
    organizer_id = models.IntegerField(default=0)
    title = models.CharField(max_length=255, null=True, blank=True)
    is_read = models.BooleanField(default=False)
    click_url = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table admin_password_resets:
class AdminPasswordReset(models.Model):
    email = models.EmailField(max_length=40, null=True, blank=True)
    token = models.CharField(max_length=40, null=True, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
#table category:
class Category(models.Model):
    name = models.TextField()
    image = models.CharField(max_length=255, null=True, blank=True)
    slug = models.TextField(null=True, blank=True)
    sort_order = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table cornjob:
class CronJob(models.Model):
    name = models.CharField(max_length=40, null=True, blank=True)
    alias = models.CharField(max_length=40, null=True, blank=True)
    action = models.TextField(null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)
    cron_schedule_id = models.IntegerField(default=0)
    next_run = models.DateTimeField(null=True, blank=True)
    last_run = models.DateTimeField(null=True, blank=True)
    is_running = models.BooleanField(default=True)
    is_default = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table cronjob_log:
class CronJobLog(models.Model):
    cron_job_id = models.IntegerField(default=0)
    start_at = models.DateTimeField(null=True, blank=True)
    end_at = models.DateTimeField(null=True, blank=True)
    duration = models.IntegerField(default=0)
    error = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table cron_schedule:
class CronSchedule(models.Model):
    name = models.CharField(max_length=40, null=True, blank=True)
    interval = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table deposit:
class Deposit(models.Model):
    user_id = models.IntegerField(default=0)
    order_id = models.IntegerField(default=0)
    method_code = models.IntegerField(default=0)
    amount = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    method_currency = models.CharField(max_length=40, null=True, blank=True)
    charge = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    rate = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    final_amount = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    detail = models.TextField(null=True, blank=True)
    btc_amount = models.CharField(max_length=255, null=True, blank=True)
    btc_wallet = models.CharField(max_length=255, null=True, blank=True)
    trx = models.CharField(max_length=40, null=True, blank=True)
    payment_try = models.IntegerField(default=0)
    status = models.IntegerField(default=0)  # 1=success, 2=pending, 3=cancel
    from_api = models.BooleanField(default=False)
    admin_feedback = models.CharField(max_length=255, null=True, blank=True)
    success_url = models.CharField(max_length=255, null=True, blank=True)
    failed_url = models.CharField(max_length=255, null=True, blank=True)
    last_cron = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table device_token:
class DeviceToken(models.Model):
    user_id = models.IntegerField(default=0)
    organizer_id = models.IntegerField(default=0)
    is_app = models.BooleanField(default=False)
    token = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table event:
class Event(models.Model):
    organizer_id = models.IntegerField(default=0)
    category_id = models.IntegerField(default=0)
    location_id = models.IntegerField(default=0)
    link = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, null=True, blank=True)
    location_address = models.TextField()
    short_description = models.TextField()
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    seats = models.IntegerField(null=True, blank=True)
    seats_booked = models.IntegerField(default=0)
    price = models.FloatField(null=True, blank=True)
    cover_image = models.CharField(max_length=255, null=True, blank=True)
    type = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    step = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    verification_details = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table extension:
class Extension(models.Model):
    act = models.CharField(max_length=40, null=True, blank=True)
    name = models.CharField(max_length=40, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    script = models.TextField(null=True, blank=True)
    shortcode = models.TextField(null=True, blank=True)
    support = models.TextField(null=True, blank=True)
    status = models.BooleanField(default=True)  # 1=enable, 0=disable
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table form:
class Form(models.Model):
    act = models.CharField(max_length=40, null=True, blank=True)
    form_data = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table frontend:
class Frontend(models.Model):
    data_keys = models.CharField(max_length=40, null=True, blank=True)
    data_values = models.TextField(null=True, blank=True)
    seo_content = models.TextField(null=True, blank=True)
    tempname = models.CharField(max_length=40, null=True, blank=True)
    slug = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table gallery_image:
class GalleryImage(models.Model):
    event_id = models.IntegerField(default=0)
    image = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table gateway:
class Gateway(models.Model):
    form_id = models.IntegerField(default=0)
    code = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=40, null=True, blank=True)
    alias = models.CharField(max_length=40, default="NULL")
    image = models.CharField(max_length=255, null=True, blank=True)
    status = models.BooleanField(default=True)  # 1=enable, 0=disable
    gateway_parameters = models.TextField(null=True, blank=True)
    supported_currencies = models.TextField(null=True, blank=True)
    crypto = models.BooleanField(default=False)  # False=fiat, True=crypto
    extra = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table gateway_currency:
class GatewayCurrency(models.Model):
    name = models.CharField(max_length=40, null=True, blank=True)
    currency = models.CharField(max_length=40, null=True, blank=True)
    symbol = models.CharField(max_length=40, null=True, blank=True)
    method_code = models.IntegerField(null=True, blank=True)
    gateway_alias = models.CharField(max_length=40, null=True, blank=True)
    min_amount = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    max_amount = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    percent_charge = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    fixed_charge = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    rate = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    gateway_parameter = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table general_settings:
class GeneralSettings(models.Model):
    site_name = models.CharField(max_length=40, null=True, blank=True)
    cancel_time = models.IntegerField(null=True, blank=True)
    payment_timeout = models.IntegerField(null=True, blank=True)
    event_verification = models.BooleanField(default=False)
    cur_text = models.CharField(max_length=40, null=True, blank=True)
    cur_sym = models.CharField(max_length=40, null=True, blank=True)
    email_from = models.CharField(max_length=40, null=True, blank=True)
    email_from_name = models.CharField(max_length=255, null=True, blank=True)
    email_template = models.TextField(null=True, blank=True)
    sms_template = models.TextField(null=True, blank=True)
    sms_body = models.CharField(max_length=255, null=True, blank=True)
    sms_from = models.CharField(max_length=255, null=True, blank=True)
    push_title = models.CharField(max_length=255, null=True, blank=True)
    push_template = models.CharField(max_length=255, null=True, blank=True)
    base_color = models.CharField(max_length=40, null=True, blank=True)
    secondary_color = models.CharField(max_length=40, null=True, blank=True)
    mail_config = models.TextField(null=True, blank=True)
    sms_config = models.TextField(null=True, blank=True)
    firebase_config = models.TextField(null=True, blank=True)
    global_shortcodes = models.TextField(null=True, blank=True)
    kv = models.BooleanField(default=False)
    ev = models.BooleanField(default=False)
    en = models.BooleanField(default=False)
    sv = models.BooleanField(default=False)
    sn = models.BooleanField(default=False)
    pn = models.BooleanField(default=True)
    force_ssl = models.BooleanField(default=False)
    maintenance_mode = models.BooleanField(default=False)
    secure_password = models.BooleanField(default=False)
    agree = models.BooleanField(default=False)
    multi_language = models.BooleanField(default=True)
    registration = models.BooleanField(default=False)
    organizer_registration = models.BooleanField(default=True)
    active_template = models.CharField(max_length=40, null=True, blank=True)
    socialite_credentials = models.TextField(null=True, blank=True)
    system_info = models.TextField(null=True, blank=True)
    last_cron = models.DateTimeField(null=True, blank=True)
    available_version = models.CharField(max_length=40, null=True, blank=True)
    system_customized = models.BooleanField(default=False)
    paginate_number = models.IntegerField(default=0)
    currency_format = models.IntegerField(default=0)
    max_gallery_images = models.IntegerField(default=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table language:
class Language(models.Model):
    name = models.CharField(max_length=40, null=True, blank=True)
    code = models.CharField(max_length=40, null=True, blank=True)
    is_default = models.BooleanField(default=False)  # 1=default, 0=non
    image = models.CharField(max_length=40, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table location:
class Location(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    slug = models.CharField(max_length=255, null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    sort_order = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 
#table notification_log:
class NotificationLog(models.Model):
    user_id = models.IntegerField(default=0)
    organizer_id = models.IntegerField(default=0)
    sender = models.CharField(max_length=40, null=True, blank=True)
    sent_from = models.CharField(max_length=40, null=True, blank=True)
    sent_to = models.CharField(max_length=40, null=True, blank=True)
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    notification_type = models.CharField(max_length=40, null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    user_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table notification_template:
class NotificationTemplate(models.Model):
    act = models.CharField(max_length=40, null=True, blank=True)
    name = models.CharField(max_length=40, null=True, blank=True)
    subject = models.CharField(max_length=255, null=True, blank=True)
    push_title = models.CharField(max_length=255, null=True, blank=True)
    email_body = models.TextField(null=True, blank=True)
    sms_body = models.TextField(null=True, blank=True)
    push_body = models.TextField(null=True, blank=True)
    shortcodes = models.TextField(null=True, blank=True)
    email_status = models.BooleanField(default=True)
    email_sent_from_name = models.CharField(max_length=40, null=True, blank=True)
    email_sent_from_address = models.CharField(max_length=40, null=True, blank=True)
    sms_status = models.BooleanField(default=True)
    sms_sent_from = models.CharField(max_length=40, null=True, blank=True)
    push_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table order:
class Order(models.Model):
    event_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    price = models.FloatField(null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    total_price = models.FloatField(null=True, blank=True)
    details = models.TextField(null=True, blank=True)
    payment_status = models.IntegerField(default=0)  # 0=pending, 1=paid...
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table organizer:
class Organizer(models.Model):
    organization_name = models.TextField()
    slug = models.TextField(null=True, blank=True)
    firstname = models.CharField(max_length=40, null=True, blank=True)
    lastname = models.CharField(max_length=40, null=True, blank=True)
    username = models.CharField(max_length=40)
    email = models.CharField(max_length=40)
    dial_code = models.CharField(max_length=40, null=True, blank=True)
    country_name = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    state = models.CharField(max_length=255, null=True, blank=True)
    zip = models.CharField(max_length=255, null=True, blank=True)
    kyc_rejection_reason = models.CharField(max_length=255, null=True, blank=True)
    provider = models.CharField(max_length=255, null=True, blank=True)
    country_code = models.CharField(max_length=40, null=True, blank=True)
    mobile = models.CharField(max_length=40, null=True, blank=True)
    balance = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    password = models.CharField(max_length=255)
    address = models.TextField(null=True, blank=True)
    status = models.BooleanField(default=True)
    kyc_data = models.TextField(null=True, blank=True)
    kv = models.IntegerField(default=0)
    ev = models.BooleanField(default=False)
    sv = models.BooleanField(default=False)
    profile_complete = models.BooleanField(default=False)
    ver_code = models.CharField(max_length=40, null=True, blank=True)
    ver_code_send_at = models.DateTimeField(null=True, blank=True)
    ts = models.BooleanField(default=False)
    tv = models.BooleanField(default=True)
    tsc = models.CharField(max_length=255, null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    ban_reason = models.CharField(max_length=255, null=True, blank=True)
    remember_token = models.CharField(max_length=255, null=True, blank=True)
    title = models.TextField()
    profile_image = models.TextField()
    cover_image = models.TextField()
    short_description = models.TextField()
    long_description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table organizer_notifications:
class OrganizerPasswordReset(models.Model):
    email = models.CharField(max_length=40, null=True, blank=True)
    token = models.CharField(max_length=40, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
#table page:
class Page(models.Model):
    name = models.CharField(max_length=40, null=True, blank=True)
    slug = models.CharField(max_length=40, null=True, blank=True)
    tempname = models.CharField(max_length=40, null=True, blank=True)
    secs = models.TextField(null=True, blank=True)
    seo_content = models.TextField(null=True, blank=True)
    is_default = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table password_resets:
class PasswordReset(models.Model):
    email = models.CharField(max_length=40, null=True, blank=True)
    token = models.CharField(max_length=40, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
#table personal_access_tokens:
class PersonalAccessToken(models.Model):
    tokenable_type = models.CharField(max_length=255)
    tokenable_id = models.BigIntegerField()
    name = models.CharField(max_length=255)
    token = models.CharField(max_length=255)
    abilities = models.TextField(null=True, blank=True)
    last_used_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table slot:
class Slot(models.Model):
    time_slot_id = models.IntegerField(default=0)
    start_time = models.CharField(max_length=40, null=True, blank=True)
    end_time = models.CharField(max_length=40, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table speaker:
class Speaker(models.Model):
    event_id = models.IntegerField(default=0)
    name = models.CharField(max_length=255, null=True, blank=True)
    designation = models.CharField(max_length=255, null=True, blank=True)
    social = models.TextField(null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table subscriber:
class Subscriber(models.Model):
    email = models.CharField(max_length=40, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table support_attachment:
class SupportAttachment(models.Model):
    support_message_id = models.IntegerField(default=0)
    attachment = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 
#table support_message:
class SupportMessage(models.Model):
    support_ticket_id = models.IntegerField(default=0)
    admin_id = models.IntegerField(default=0)
    message = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table support_ticket:
class SupportTicket(models.Model):
    user_id = models.IntegerField(default=0)
    organizer_id = models.IntegerField(default=0)
    name = models.CharField(max_length=40, null=True, blank=True)
    email = models.CharField(max_length=40, null=True, blank=True)
    ticket = models.CharField(max_length=40, null=True, blank=True)
    subject = models.CharField(max_length=255, null=True, blank=True)
    status = models.IntegerField(default=0)  # 0=open,1=answered,2=replied,3=closed
    priority = models.IntegerField(default=0)  # 1=low,2=medium,3=high
    last_reply = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table time_slot:
class TimeSlot(models.Model):
    event_id = models.IntegerField(default=0)
    date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table transaction:
class Transaction(models.Model):
    user_id = models.IntegerField(default=0)
    organizer_id = models.IntegerField(default=0)
    amount = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    charge = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    post_balance = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    trx_type = models.CharField(max_length=40, null=True, blank=True)
    trx = models.CharField(max_length=40, null=True, blank=True)
    details = models.CharField(max_length=255, null=True, blank=True)
    remark = models.CharField(max_length=40, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table update_log:
class UpdateLog(models.Model):
    version = models.CharField(max_length=40, null=True, blank=True)
    update_log = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table user:
class User(AbstractUser):
    dial_code = models.CharField(max_length=40, null=True, blank=True)
    country_name = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    state = models.CharField(max_length=255, null=True, blank=True)
    zip = models.CharField(max_length=255, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    kyc_rejection_reason = models.CharField(max_length=255, null=True, blank=True)
    provider = models.CharField(max_length=255, null=True, blank=True)
    provider_id = models.CharField(max_length=255, null=True, blank=True)
    country_code = models.CharField(max_length=40, null=True, blank=True)
    mobile = models.CharField(max_length=40, null=True, blank=True)
    balance = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    kyc_data = models.TextField(null=True, blank=True)
    kv = models.IntegerField(default=0)
    ev = models.BooleanField(default=False)
    sv = models.BooleanField(default=False)
    profile_complete = models.BooleanField(default=False)
    ver_code = models.CharField(max_length=40, null=True, blank=True)
    ver_code_send_at = models.DateTimeField(null=True, blank=True)
    ts = models.BooleanField(default=False)
    tv = models.BooleanField(default=True)
    tsc = models.CharField(max_length=255, null=True, blank=True)
    ban_reason = models.CharField(max_length=255, null=True, blank=True)
    remember_token = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table user_event:
class UserEvent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table user_login:
class UserLogin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ip = models.CharField(max_length=40, null=True, blank=True)
    organizer_id = models.IntegerField(default=0)
    city = models.CharField(max_length=40, null=True, blank=True)
    country = models.CharField(max_length=40, null=True, blank=True)
    country_code = models.CharField(max_length=40, null=True, blank=True)
    longitude = models.CharField(max_length=40, null=True, blank=True)
    latitude = models.CharField(max_length=40, null=True, blank=True)
    browser = models.CharField(max_length=40, null=True, blank=True)
    os = models.CharField(max_length=40, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table user_organizer:
class UserOrganizer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organizer_id = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table withdrawal:
class Withdrawal(models.Model):
    method_id = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organizer_id = models.IntegerField(default=0)
    amount = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    currency = models.CharField(max_length=40, null=True, blank=True)
    rate = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    charge = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    trx = models.CharField(max_length=40, null=True, blank=True)
    final_amount = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    after_charge = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    withdraw_information = models.TextField(null=True, blank=True)

    STATUS_CHOICES = (
        (1, 'success'),
        (2, 'pending'),
        (3, 'cancel'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=2)

    admin_feedback = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#table withdraw_method:
class WithdrawMethod(models.Model):
    form_id = models.IntegerField(default=0)
    name = models.CharField(max_length=40, null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    min_limit = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    max_limit = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    fixed_charge = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    rate = models.DecimalField(max_digits=28, decimal_places=8, default=0)
    percent_charge = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    currency = models.CharField(max_length=40, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)